### ISSUE TITLE
您好，我在运行2.API_serve/KG_service.py时，加载失败，问答数据换成了2GB的，大约300多万条

### ISSUE THREAD

**Issue by zuole** [ZJJDJJ/chatbot_simbert#1]
想问一下，加载的问题出在哪里？如何解决呢？
用的是Linux服务器 显卡是2080ti 显存容量11GB

Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 0.717 seconds.
Prefix dict has been built successfully.

在此之后就没有任何动静了

**Comment by ZJJDJJ** [comment]
300万的数据，需要把里面的bool检索关掉，因为这个数据量会让bool检索的倒排表初始化特别慢。
建议从小数据量开始，如果数据量大的话，就把bool关了
另外怎么有这么多数据，闲聊类型的嘛，可不可以分享一下，嘿嘿

**Comment by zuole** [comment]
> 300万的数据，需要把里面的bool检索关掉，因为这个数据量会让bool检索的倒排表初始化特别慢。
> 建议从小数据量开始，如果数据量大的话，就把bool关了
> 另外怎么有这么多数据，闲聊类型的嘛，可不可以分享一下，嘿嘿

可以的，方便给个联系方式嘛？qq或者邮箱啥的

**Comment by ZJJDJJ** [comment]
zhuo18817775844@163.com，2g可能邮箱传不过来。或者帮忙放百度网盘，这样快一点啊~

**Comment by pinro3** [comment]
大哥,1719980170@qq.com,可以发给我一份吗,好人一生平安!

**Comment by dh12306** [comment]
> > 300万的数据，需要把里面的bool检索关掉，因为这个数据量会让bool检索的倒排表初始化特别慢。
> > 建议从小数据量开始，如果数据量大的话，就把bool关了
> > 另外怎么有这么多数据，闲聊类型的嘛，可不可以分享一下，嘿嘿
> 
> 可以的，方便给个联系方式嘛？qq或者邮箱啥的

你好，837670785@qq.com，求一份数据，好人一生平安啊
